// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_login_tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailLoginToken = `-- name: ConsumeEmailLoginToken :one
DELETE FROM email_login_tokens
WHERE token_hash = $1
RETURNING token_hash, email, created_at, expires_at
`

func (q *Queries) ConsumeEmailLoginToken(ctx context.Context, tokenHash string) (EmailLoginToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailLoginToken, tokenHash)
	var i EmailLoginToken
	err := row.Scan(
		&i.TokenHash,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const saveEmailLoginToken = `-- name: SaveEmailLoginToken :exec
INSERT INTO email_login_tokens (token_hash, email, expires_at)
VALUES ($1, $2, $3)
`

type SaveEmailLoginTokenParams struct {
	TokenHash string
	Email     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SaveEmailLoginToken(ctx context.Context, arg SaveEmailLoginTokenParams) error {
	_, err := q.db.Exec(ctx, saveEmailLoginToken, arg.TokenHash, arg.Email, arg.ExpiresAt)
	return err
}
