// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailChangeConfirmationToken struct {
	TokenHash string
	UserID    pgtype.UUID
	NewEmail  string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type EmailChangeVerifyToken struct {
	TokenHash string
	UserID    pgtype.UUID
	NewEmail  string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type EmailLoginToken struct {
	TokenHash string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type File struct {
	ID        pgtype.UUID
	Filename  string
	Size      int32
	MimeType  string
	Key       string
	OwnerID   pgtype.UUID
	FileType  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Share struct {
	ID           pgtype.UUID
	Name         string
	PasswordHash pgtype.Text
	OwnerID      pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ExpiresOn    pgtype.Timestamptz
}

type SharesFile struct {
	FileID    pgtype.UUID
	ShareID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Upload struct {
	ClientID  pgtype.UUID
	OwnerID   pgtype.UUID
	FileName  string
	Size      int64
	MimeType  string
	Key       string
	UploadID  pgtype.Text
	Parts     int32
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Name           string
	Email          string
	CredentialType string
	Membership     string
	BannedUntil    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Role           string
	LastLogin      pgtype.Timestamptz
}
