// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAndReturnId = `-- name: CreateUserAndReturnId :one
INSERT INTO users (id, name, email, credential_type)
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3
)
RETURNING id
`

type CreateUserAndReturnIdParams struct {
	Name           string
	Email          string
	CredentialType string
}

func (q *Queries) CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUserAndReturnId, arg.Name, arg.Email, arg.CredentialType)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateLastLoginByUserID = `-- name: UpdateLastLoginByUserID :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLoginByUserID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLoginByUserID, id)
	return err
}
